elasticsearch:
  restart: always
  image: elasticsearch:7.5.0
  container_name: elasticsearch
  environment:
    # - cluster.initial_master_nodes[0]=localhost
    - discovery.type=single-node
    - http.cors.enabled=true
    - http.cors.allow-credentials=true
    - http.cors.allow-headers=*
    - http.cors.allow-origin=*
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ports:
    - 9222:9200
    - 9333:9300
  volumes:
    - es_data:/usr/share/elasticsearch/data
    - es_logs:/usr/share/elasticsearch/logs
