jenkins:
  image: jenkinsci/blueocean
  container_name: qa-jenkins
  restart: always
  user: root
  ports:
    - 8080:8080
    - 50000:50000
  volumes:
    - ../data/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock