version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: QA
      MONGO_INITDB_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: QA
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      TZ: Asia/Shanghai

volumes:
  mongo_db: