version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      TZ: Asia/Shanghai
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      TZ: Asia/Shanghai

volumes:
  mongo_db: