redis:
   container_name: redis
   image: redis
   ports:
     - "6379:6379"
   volumes:
     - ../data/redis:/data
   entrypoint: 
    redis-server --appendonly yes --requirepass 1qaz2wsx3edc 
   restart: always